-- AlterTable
ALTER TABLE "Stats" ALTER COLUMN "bonusCap" SET DEFAULT 5,
ALTER COLUMN "bonusCap" SET DATA TYPE DECIMAL(65,0),
ALTER COLUMN "bonusProgress" SET DEFAULT 0,
ALTER COLUMN "bonusProgress" SET DATA TYPE DECIMAL(65,0);
