export { default as logo } from "./logo.png"
export { default as button } from "./button.png"
export { default as battleIcon } from "./skill icons/Battling_icon.png"
export { default as dungioneeringIcon } from "./skill icons/dungioneering_icon.png"
export { default as miningIcon } from "./skill icons/Mining_icon.png"
export { default as woodcuttingIcon } from "./skill icons/Woodcutting_icon.png"
export { default as quarryingIcon } from "./skill icons/quarrying_icon.png"
export { default as runecraftingIcon } from "./skill icons/runecrafting_icon.png"
export { default as jewelcraftingIcon } from "./skill icons/jewelcrafting_icon.png"
export { default as herbloreIcon } from "./skill icons/Herblore_icon.png"
export { default as marketIcon } from "./other icons/market_icon.png"
export { default as clansIcon } from "./other icons/clans_icon.png"
export { default as chatIcon } from "./other icons/chat_icon.png"
export { default as settingsIcon } from "./other icons/settings_icon.png"
export { default as swordIcon } from "./equipment icons/Weapon_slot.png"
export { default as helmetIcon } from "./equipment icons/Head_slot.png"
export { default as armorIcon } from "./equipment icons/Body_slot.png"
export { default as gauntletsIcon } from "./equipment icons/Hands_slot.png"
export { default as legsIcon } from "./equipment icons/Legs_slot.png"
export { default as bootsIcon } from "./equipment icons/Feet_slot.png"
export { default as hammerIcon } from "./equipment icons/hammer.png"
export { default as pickaxeIcon } from "./equipment icons/pickaxe.png"
export { default as hatchetIcon } from "./equipment icons/axe.png"
export { default as OpenEye } from "./other icons/eye-open.svg?react"
export { default as ClosedEye } from "./other icons/eye-close.svg?react"