export { default as logo } from "./logo.png"
export { default as button } from "./button.png"
export { default as battleIcon } from "./Battling_icon.png"
export { default as dungioneeringIcon } from "./dungioneering_icon_small.png"
export { default as miningIcon } from "./Mining_icon.png"
export { default as woodcuttingIcon } from "./Woodcutting_icon.png"
export { default as quarryingIcon } from "./quarrying_icon.png"
export { default as runecraftingIcon } from "./runecrafting_icon.png"
export { default as jewelcraftingIcon } from "./jewelcrafting_icon.png"
export { default as herbloreIcon } from "./Herblore_icon.png"
export { default as marketIcon } from "./market_icon.png"
export { default as clansIcon } from "./clans_icon.png"
export { default as chatIcon } from "./chat_icon.png"
export { default as swordIcon } from "./equipment icons/Weapon_slot.png"
export { default as helmetIcon } from "./equipment icons/Head_slot.png"
export { default as armorIcon } from "./equipment icons/Body_slot.png"
export { default as gauntletsIcon } from "./equipment icons/Hands_slot.png"
export { default as legsIcon } from "./equipment icons/Legs_slot.png"
export { default as bootsIcon } from "./equipment icons/Feet_slot.png"
export { default as hammerIcon } from "./equipment icons/hammer.png"
export { default as pickaxeIcon } from "./equipment icons/pickaxe.png"
export { default as hatchetIcon } from "./equipment icons/axe.png"
export { default as showpassword } from "./show.png"
export { default as hidepassword } from "./hide.png" 